### PR TITLE
Intel defaults fix

### LINKED ISSUE #44: Default values break some intel compilers
Use of certain pure intrinsic functions to initialize variables at definition time breaks some intel compilers.  These have been unrolled.

I prefer the extensible implementation, as it automatically adjusted to parameter changes.  This can be improved as a feature request later.

### PR DESCRIPTION
**Pull request by garrettwrong**
Closes #44 . 

I introduced this bug, fixing.  I prefer the other way, but that would reduce compatibility.

### CODE REVIEW

**Comment by ypetrov** [comment]
I am not sure about this approach to setting default values:
    mpwrsou(0:ngena) = (/ 1., 3. ,3., 3., 3./)
What if ngena is changed in param.f90?
Originally, such arrays (which depend on values in param.f90) were  
populated in a do loop , like "do k=1,ngena".
Can we simply state mpwrsou(1:) =3.  ?
--Yuri


Quoting Garrett Wright <notifications@github.com>:

**Comment by garrettwrong** [comment]
Yes, that is a trade off. In the issue I noted that I recrated that loop, but some intel fortrans did not like. The trade off is that the defaults are not extensible.

Ideally yes, all the default values would be simple.  I just chose to what I found in the code.  If they can all be trivial defaults that would be great.

**Comment by garrettwrong** [comment]
Note that these defaults are different, in that they exist at compile time, not runtime.

(to be clear, I don't like it either, but unless it is true all the defaults can be trivial at compile time (I think they cannot), this might have to suffice until it is worth circling back to implement.  Honestly so much of the parameter size logic is in need of rework that it is its own micro project.)

**Comment by garrettwrong** [comment]
opened issue #46 with your concern. Merging.

**Pull request merged**
