### PR TITLE
updates in fr* subroutines related to the new derived type setup0

### PR DESCRIPTION
**Pull request by ypetrov**
Some of lrzmax and lrz were missed from conversion

### CODE REVIEW

**Comment by garrettwrong** [comment]
Okay, nice.  Couple things we'll need to do to get this in: 

Any subroutine or function that uses something from a module (like setup0), we should have `use cqlconf_mod, only : setup0`.  This is different than f77 where everything was global.  The `public` in a module just means you _can_ use it, `private` is hidden outside the module. We still need to use associate things so the compiler knows where they come from. This is also (with the help of .mod files) how it knows about type,kind, rank, and other details.  In particular the mode dangerous things about what we're doing are implicit none, then mixing f77 and f90 code.  Both allow this to happen.  In f90 with implicit none, these problems virtually go away.

The test folder, if we can move it to `ci/nstx` that would be good.  To do that with git, you would say `git mv test_nstx ci/nstx`.  Lets change the output netcdf and postscript file to reference.{nc,ps} respectively.  I can explain more about why another time.

I would do the modifications for you, but I don't want it to complicate your experience with git right now.

**Comment by garrettwrong** [comment]
also we'll need to update the makefile depends such that the setup0 changed freya codes depend on cqlcomm.o.

**Comment by ypetrov** [comment]
Do I need to approve anything?
I don't see where.



Quoting Garrett Wright <notifications@github.com>:

**Comment by garrettwrong** [comment]
No, I'd prefer we fix the changes all the way.  I'll approve then. Thanks

**Pull request merged**
